#!/bin/sh
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
[ -r .git/ctags_ignore ] && EXCLUDE="--exclude=@.git/ctags_ignore"

test -d .git || exit 0

mkdir .git/tags_lock 2>/dev/null || exit 0
trap "rm -rf .git/tags_lock; rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git ${EXCLUDE}
mv .git/tags.$$ .git/tags
