#!/bin/sh
# http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
set -e
mkdir .git/tags_lock 2>/dev/null || exit 0
trap "rm -rf .git/tags_lock; rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --exclude=@.git/ctags_ignore
mv .git/tags.$$ .git/tags
