#!/usr/bin/env sh
# Configure flags for Vim
#
# Add for OSX:
# export CPPFLAGS=-I/opt/X11/include

./configure \
    --with-compiledby=whiteinge \
    --prefix=$HOME \
    --with-features=huge \
    --enable-multibyte \
    --with-tlib=ncurses \
    --enable-cscope \
    --enable-terminal=no \
    --enable-gui=no \
    --with-x \
    --enable-cscope \
    --enable-luainterp
